In [52]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [53]:
df=pd.read_csv('train.txt',sep=';',header=None,names=['text','emotion'])

In [54]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [55]:
df.isna().sum()

text       0
emotion    0
dtype: int64

In [56]:
df['emotion'].unique()

array(['sadness', 'anger', 'love', 'surprise', 'fear', 'joy'],
      dtype=object)

In [57]:
emotions=['sadness', 'anger', 'love', 'surprise', 'fear', 'joy']
dict={}
i=0
for emo in emotions:
    dict[emo]=i
    i+=1

In [58]:
df['emotion']=df['emotion'].map(dict)

Text cleaning
1.doing thing in lowercase

In [59]:
df['text']=df['text'].apply(lambda x:x.lower())

2. removing punctuation

In [60]:
import string
print(string.punctuation)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

In [61]:
def remove_punc(txt):
    return txt.translate(str.maketrans('','',string.punctuation))

In [62]:
# df['text']=df['text'].apply(lambda txt:remove_punc(txt))
df['text']=df['text'].apply(remove_punc)

In [63]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

remove numbers

In [64]:
def remove_num(txt):
    s=''
    for c in txt:
        if not c.isdigit():
            s+=c
    return s 
df['text']=df['text'].apply(remove_num)

url and links we have to remove

In [65]:
import re
def remove_link(txt):
    # This pattern looks for http, https, or www and grabs everything until the next space
    pattern = r'https?://\S+|www\.\S+'
    return re.sub(pattern, '', txt)
df['text']=df['text'].apply(remove_link)

remove emojii

In [66]:
def remove_emojii(txt):
    s=''
    for c in txt:
        if c.isascii():
            s+=c
    return s 
df['text']=df['text'].apply(remove_emojii)

why we do text cleaning beacuse in ml txt is treated as data ,they are not gonaa read or understand so, keep data less complex for better traning

most important part of text cleaning that is removing stopword

In [67]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\anshu\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\anshu\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [68]:
stop_words=set(stopwords.words('english'))

In [69]:
len(stop_words)

198

In [70]:
def remove(txt):
    words=word_tokenize(txt)
    new=[]
    for tok in words:
        if tok not in stop_words:
            new.append(tok)
    return " ".join(new)

In [71]:
df['text']=df['text'].apply(remove)

In [72]:
df.iloc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'

In [73]:
df.head()

                                                text  emotion
0                              didnt feel humiliated        0
1  go feeling hopeless damned hopeful around some...        0
2          im grabbing minute post feel greedy wrong        1
3  ever feeling nostalgic fireplace know still pr...        2
4                                    feeling grouchy        1

In [74]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df['text'], df['emotion'], test_size=0.20, random_state=42)

first we use bag word and see

In [75]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
bow_vectorizer=CountVectorizer()

In [76]:
X_train_bow=bow_vectorizer.fit_transform(X_train)
X_test_bow=bow_vectorizer.transform(X_test)

In [77]:
X_train_bow.shape

(12800, 13359)

In [78]:
X_test_bow.shape

(3200, 13359)

In [79]:
from sklearn.naive_bayes import MultinomialNB
NB_model=MultinomialNB()# we not gaussian naviebyes because it may not normaly distributed

In [80]:
NB_model.fit(X_train_bow,y_train)

MultinomialNB()

In [81]:
y_pred=NB_model.predict(X_test_bow)

In [82]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_pred)

In [83]:
accuracy

0.7678125

let check accuracy with tf_idf

In [84]:
TF_IDF_vectorizer=TfidfVectorizer()

In [85]:
X_train_TF_IDF=TF_IDF_vectorizer.fit_transform(X_train)
X_test_TF_IDF=TF_IDF_vectorizer.transform(X_test)

In [86]:
X_test_TF_IDF.shape

(3200, 13359)

In [87]:
NB2_model=MultinomialNB()
NB2_model.fit(X_train_TF_IDF,y_train)

MultinomialNB()

In [88]:
y_pred=NB2_model.predict(X_test_TF_IDF)

In [89]:
accuracy=accuracy_score(y_test,y_pred)
accuracy

0.6609375

using another model logistic regression

In [90]:
from sklearn.linear_model import LogisticRegression
log_model_bag=LogisticRegression(max_iter=1000)
log_model_TF_IDF=LogisticRegression(max_iter=1000)

In [91]:
log_model_bag.fit(X_train_bow,y_train)
log_model_TF_IDF.fit(X_train_TF_IDF,y_train)

LogisticRegression(max_iter=1000)

In [92]:
y_pred_bag=log_model_bag.predict(X_test_bow)
y_pred_TF_IDF=log_model_bag.predict(X_test_TF_IDF)

In [94]:
accuracy_bag=accuracy_score(y_test,y_pred_bag)
accuracy_TF_IDF=accuracy_score(y_test,y_pred_TF_IDF)

In [95]:
print(accuracy_bag,accuracy_TF_IDF)

0.88875 0.825625

here logistic regession with bag of words algo work good but still i don't do hyper parameter tunning
so,lets do

In [96]:
from sklearn.model_selection import GridSearchCV
log_model3=LogisticRegression()

In [97]:
params = {
    'C': [0.01, 0.1, 1, 10, 100],
    'penalty': ['l1', 'l2'],
    'solver': ['saga'],
    'max_iter': [1000]
}
grid=GridSearchCV(estimator=log_model3,param_grid=params,cv=5,scoring='accuracy',n_jobs=-1)

In [98]:
# grid.fit(X_train_bow,y_train)
# y_pred_bag=grid.predict(X_test_bow)
# accuracy_bag=accuracy_score(y_test,y_pred_bag)

In [112]:
grid.fit(X_train_TF_IDF,y_train)
y_pred_bag=grid.predict(X_test_TF_IDF)
accuracy_bag=accuracy_score(y_test,y_pred_bag)

d:\mtech\projects\ML\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
d:\mtech\projects\ML\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1160: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
d:\mtech\projects\ML\venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

In [113]:
grid.best_estimator_

LogisticRegression(C=10, max_iter=1000, penalty='l1', solver='saga')

In [114]:
accuracy_bag

0.8978125

In [116]:
import joblib
joblib.dump(grid.best_estimator_,'Emotion_dectector_.pkl')
joblib.dump(bow_vectorizer,'TF_IDF_vectorizer.pkl')

['TF_IDF_vectorizer.pkl']

Lets try svm

In [ ]:
from sklearn.svm import LinearSVC

# Best for text classification
param_grid_linear = {
    'C': [0.01, 0.1, 1, 10, 100],
    'loss': ['hinge', 'squared_hinge'],
    'penalty': ['l2'], # liblinear multiclass mostly supports l2
    'max_iter': [2000]
}

In [100]:
from sklearn.model_selection import GridSearchCV
grid_svm=GridSearchCV(estimator=LinearSVC(),param_grid=param_grid_linear,cv=5,scoring='accuracy',n_jobs=-1)

In [101]:
grid_svm.fit(X_train_TF_IDF,y_train)

GridSearchCV(cv=5, estimator=LinearSVC(), n_jobs=-1,
             param_grid={'C': [0.01, 0.1, 1, 10, 100],
                         'loss': ['hinge', 'squared_hinge'], 'max_iter': [2000],
                         'penalty': ['l2']},
             scoring='accuracy')

In [103]:
pred=grid_svm.predict(X_test_TF_IDF)

In [104]:
accuracy_TF_IDF=accuracy_score(y_test,pred)

In [105]:
accuracy_TF_IDF

0.8934375

In [111]:
txt_vec = TF_IDF_vectorizer.transform(["Learning lifelong process"])
ypred = grid_svm.predict(txt_vec)

print(ypred)

[5]